version: '3'

services:
  web:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./src/:/var/www/testapp
      - ./images/nginx/site.conf:/etc/nginx/conf.d/default.conf
      - ./images/nginx/m2-config/nginx.conf:/var/www/testapp/nginx.conf
    restart: always
    working_dir: /var/www/testapp
    depends_on:
      - php
      - mysql
      - elasticsearch
  php:
    build:
      context: ./images/php
    restart: always
    container_name: php
    working_dir: /var/www/testapp
    volumes:
      - ./src/:/var/www/testapp
    expose:
      - "9000"
  mysql:
    image: mysql:8.0
    restart: always
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./images/mysql/initdb:/docker-entrypoint-initdb.d
      - ./data/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
    expose:
      - "3306"
  adminer:
    image: adminer
    restart: always
    container_name: adminer
    volumes:
      - ./images/adminer/php-custom.ini:/usr/local/etc/php/conf.d/php-custom.ini
    expose:
      - "8080"
    ports:
      - 8088:8080
    environment:
      - ADMINER_DEFAULT_SERVER=mysql
      - ADMINER_DESIGN="pappu687"
  elasticsearch:
        image: elasticsearch:7.6.2
        container_name: elasticsearch
        ports:
            - 9200:9200
            - 9300:9300
        environment:
            "discovery.type": "single-node"